# Generated by Django 5.1 on 2024-09-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioDeTrabajo',
            fields=[
                ('idEspacio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspacio', models.CharField(max_length=45)),
                ('estadoEspacio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionEstado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=45)),
                ('apellidoUsuario', models.CharField(max_length=45)),
                ('correoUsuario', models.EmailField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('idTablero', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTablero', models.CharField(max_length=45)),
                ('idEspacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.espaciodetrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('idLista', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLista', models.CharField(max_length=45)),
                ('maxWip', models.IntegerField()),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.estado')),
                ('idTablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.tablero')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('idTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreActividad', models.CharField(max_length=45)),
                ('descripcionTarjeta', models.TextField(blank=True)),
                ('fechaCreacion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('etiqueta', models.CharField(blank=True, max_length=45)),
                ('idLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.lista')),
                ('idUsuarioAsignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('idTask', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionTask', models.TextField()),
                ('estadoTask', models.BooleanField(default=True)),
                ('vencimientoTask', models.DateField()),
                ('idTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosAsignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.CharField(max_length=45)),
                ('fechaAsignacion', models.DateField()),
                ('idEspacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.espaciodetrabajo')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forutask_api.usuario')),
            ],
        ),
    ]
