# Generated by Django 5.1 on 2024-09-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forutask_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='password',
        ),
    ]
