# Generated by Django 5.1 on 2024-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forutask_api', '0003_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
