# Generated by Django 5.1 on 2024-10-18 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forutask_api', '0004_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='etiqueta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='etiquetas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nombreLista',
            field=models.CharField(default='lista generica', max_length=45),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='descripcionTarjeta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fechaVencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='idUsuarioAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
