# Generated by Django 5.1 on 2024-10-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forutask_api', '0005_remove_tarjeta_etiqueta_tarjeta_etiquetas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='etiquetas',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
    ]
